version: '3'

services:
  php:
    container_name: docker-test-php
    build: docker/php
    ports:
      - '9999:80'
    volumes:
      - .:/var/www/html

  redis:
    container_name: docker-test-redis
    build: docker/redis